// #107: team histories. (1) The page's own bracket code (public/index.html) against the Python
// port in team_history.py, for every team in every archived national flight: the Python side is
// generated by this test, under the network guard, into a temporary directory inside the
// repository that is removed afterwards (M8). (2) The route, /api/v1/teams/{id}/history, with the
// rest of the data API and the #90 gate. (3) The page's history request under refusals (#92), and
// the words it shows for a post-season entry (M4).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveResource, dataApi } from '../api/data-api.mjs';
import { assetPath } from '../api/archive-reader.mjs';
import { gate } from '../api/session.mjs';

const repo = fileURLToPath(new URL('..', import.meta.url));
const root = new URL('../public/', import.meta.url);
const html = (await readFile(new URL('index.html', root), 'utf8')).replace(/\r\n/g, '\n');
// From the line that starts `head` to the end of the function (or statement) that `last` names.
const block = (head, last = head) => {
  const start = html.indexOf('\n' + head) + 1;
  const from = html.indexOf(last, start);
  const end = html.indexOf('\n    }\n', from) + 6;
  assert.ok(start > 0 && from >= start && end > from, `${head} not found in index.html`);
  return html.slice(start, end);
};
const json = async p => { try { return JSON.parse(await readFile(new URL(p, root), 'utf8')); } catch { return null; } };

test('page brackets and the Python port agree on every national team', async (t) => {
  const tmp = mkdtempSync(join(repo, '.parity-'));
  let py;
  try {
    const out = join(tmp, 'parity.json');
    const run = spawnSync(process.env.PYTHON || 'python', ['team_history.py', '--parity', out], {
      cwd: repo, encoding: 'utf8',
      env: { ...process.env, PYTHONPATH: join('tests', 'netguard'), HTTPS_PROXY: 'http://127.0.0.1:9', HTTP_PROXY: 'http://127.0.0.1:9', NETGUARD_REPORT: '1' },
    });
    assert.equal(run.status, 0, run.stderr || run.error?.message);
    assert.match(run.stderr, /netguard: 0 network attempt/, 'the Python side ran under the guard');
    py = JSON.parse(readFileSync(out, 'utf8'));
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
  const page = new Function([block('    function bracketName('), block('    function gameWinner('), block('    function knockoutGames('),
    block('    function buildBrackets('), 'return { knockoutGames, buildBrackets };'].join('\n'))();
  const cat = await json('data/sources.json');
  let n = 0; const bad = [];
  const warn = console.warn; console.warn = () => {};
  try {
    for (const s of Object.values(cat.seasons)) for (const ev of Object.values(s.national || {})) {
      const h = await json(`archive/api/Event/get-event-schedule-or-standings/${ev.eventId}.json`);
      for (const d of (h?.data?.girlsDivAndFlightList || [])) for (const f of (d.flightList || [])) {
        const games = (await json(`archive/api/Event/get-schedules-by-flight/${ev.eventId}/${f.flightID}/0.json`))?.data || [];
        const st = (await json(`archive/api/Event/get-standings-by-div-and-flight/${d.divisionID}/${f.flightID}/${ev.eventId}.json`))?.data;
        const blocks = (Array.isArray(st) ? st : st ? [st] : []).filter(b => b && (b.teamStandings || []).length);
        const tier = (ev.tierLabels || {})[f.flightName] || f.flightName;
        const ko = page.knockoutGames(games, blocks, ((ev.dataGaps || {})[f.flightID] || {}).omitFromBracket || []);
        const br = ko.length ? page.buildBrackets(ko, f.flightName, tier) : null;
        const main = br && br.list.find(b => b.isMain), cup = br && br.list.find(b => b.path === 'L1');
        const reached = (b, id) => b.rounds.filter(r => r.games.some(e => e.game.hometeamID === id || e.game.awayteamID === id)).map(r => r.name).slice(-1)[0] || null;
        for (const id of [...new Set(games.flatMap(g => [g.hometeamID, g.awayteamID]).filter(Boolean))]) {
          const name = (games.find(g => g.hometeamID === id) || {}).homeTeam || (games.find(g => g.awayteamID === id) || {}).awayTeam;
          const js = [main ? reached(main, id) : null, !!(br && br.champion && br.champion === name),
            cup && reached(cup, id) ? `${cup.name}: ${reached(cup, id)}` : null];
          n++;
          if (JSON.stringify(js) !== JSON.stringify(py[`${ev.eventId}/${f.flightID}/${id}`])) bad.push([ev.eventId, f.flightID, id, name, js, py[`${ev.eventId}/${f.flightID}/${id}`]]);
        }
      }
    }
  } finally { console.warn = warn; }
  t.diagnostic(`${n} team-flights compared, ${bad.length} differ`);
  assert.equal(Object.keys(py).length, n);
  assert.ok(n > 2000, `only ${n} team-flights`);
  assert.deepEqual(bad, []);
});

const request = (path, options) => new Request('https://ecnl.nextonetwo.com' + path, options);
const env = { ASSETS: { async fetch(req) {
  try { return new Response(await readFile(new URL(new URL(req.url).pathname.slice(1), root)), { headers: { 'content-type': 'application/json', etag: '"fixture"' } }); }
  catch { return new Response('<html>missing</html>', { status: 404 }); }
} } };

test('the history route: ids validated like every route, validators forwarded, JSON 404 for no file', async () => {
  assert.deepEqual(resolveResource('/api/v1/teams/55477/history'), { kind: 'history', team: '55477' });
  assert.equal(assetPath({ kind: 'history', team: '55477' }), '/archive/history/55477.json');
  for (const bad of ['0', '01', '-1', 'abc', '1.5', '%2e%2e%2f', '55477%2F..']) assert.equal(resolveResource(`/api/v1/teams/${bad}/history`).status, 400, bad);
  for (const none of ['/api/v1/teams/55477', '/api/v1/teams/55477/history/', '/api/v1/teams']) assert.equal(resolveResource(none).status, 404, none);
  for (const method of ['GET', 'HEAD']) {
    const missing = await dataApi(request('/api/v1/teams/1/history', { method }), env);
    assert.equal(missing.status, 404);
    assert.equal(missing.headers.get('cache-control'), 'no-store');
    if (method === 'GET') assert.deepEqual(await missing.json(), { ok: false, error: 'Not found' });
    const conditional = await dataApi(request('/api/v1/teams/55477/history', { method, headers: { 'if-none-match': '"fixture"' } }), { ASSETS: { fetch(req) {
      assert.equal(new URL(req.url).pathname, '/archive/history/55477.json');
      assert.equal(req.headers.get('if-none-match'), '"fixture"');
      return new Response(null, { status: 304, headers: { etag: '"fixture"' } });
    } } });
    assert.equal(conditional.status, 304);
    assert.equal(await conditional.text(), '');
  }
});

// The history files are committed separately from the code (#107): without them this is skipped.
const hasHistory = existsSync(new URL('archive/history/55477.json', root));
test('every history file is served byte for byte by one asset read', { skip: !hasHistory && 'no team-history data in this checkout' }, async () => {
  let count = 0;
  for (const file of await readdir(new URL('archive/history/', root))) {
    const match = /^(\d+)\.json$/.exec(file);
    if (!match) continue;
    let reads = 0;
    const response = await dataApi(request(`/api/v1/teams/${match[1]}/history`), { ASSETS: { fetch(req) { reads++; return env.ASSETS.fetch(req); } } });
    assert.equal(response.status, 200, file);
    assert.deepEqual(Buffer.from(await response.arrayBuffer()), await readFile(new URL('archive/history/' + file, root)));
    assert.equal(reads, 1);
    assert.equal(response.headers.get('cache-control'), 'no-cache');
    count++;
  }
  assert.ok(count > 1800, `only ${count} history files`);
});

test('the history route is behind the #90 gate like every /api/v1 route', async () => {
  const points = [];
  const limiter = () => ({ async limit() { return { success: true }; } });
  const genv = { SESSION_SECRET: 's'.repeat(40), RL_SESSION: limiter(), RL_ANON: limiter(), RL_IP: limiter(), API_EVENTS: { writeDataPoint(p) { points.push(p); } } };
  const g = await gate(request('/api/v1/teams/55477/history', { headers: { 'cf-connecting-ip': '203.0.113.9' } }), genv, Date.UTC(2026, 8, 30));
  assert.equal(g.session, 'none');
  assert.deepEqual(points.at(-1).blobs.slice(0, 2), ['anon-missing', 'history']);
});

// ---- the page: getTeamHistory under refusals (#92), in Node with a stubbed fetch and clock ----
const CODE = [
  block('    let sessionRenewAt = 0', 'function noteSession('),
  block('    async function fetchJSON(', 'function failedFlightPanel('),
  block('    const teamHistoryMemo = {};', 'function historyAvailable('),
].join('\n');

function page(answer) {
  const calls = [], clock = { t: 1e12 };
  const fetch = async (url, options = {}) => {
    calls.push(`${options.method || 'GET'} ${url}`);
    if (url === '/') return new Response(null, { status: 200 });
    const a = answer(url);
    if (a instanceof Error) throw a;
    const text = a.raw ?? JSON.stringify(a.body ?? (a.status === 429 ? { ok: false, error: 'Too many requests.' } : {}));
    return new Response(text, { status: a.status, headers: { 'content-type': 'application/json', 'x-ecnl-session': a.session || 'ok' } });
  };
  const esc = s => String(s).replace(/[&<>"']/g, c => `&#${c.charCodeAt(0)};`);
  const api = new Function('LIVE', 'fetch', 'Date', 'dataUrl', 'esc',
    CODE + '\nreturn { getTeamHistory, historyAvailable, retryText, isRefusal };')(
    false, fetch, { now: () => clock.t }, p => '/api/v1/' + p, esc);
  const apiCalls = () => calls.filter(c => c.startsWith('GET /api/v1/'));
  return { ...api, calls, apiCalls, clock };
}
const DOC = { schema: 1, teamID: 55477, squads: [{ seasons: [] }] };

test('page history: 200 is kept for the session, one request', async () => {
  const p = page(() => ({ status: 200, body: DOC }));
  for (let i = 0; i < 5; i++) assert.deepEqual(await p.getTeamHistory(55477), DOC);
  assert.deepEqual(p.apiCalls(), ['GET /api/v1/teams/55477/history']);
  assert.ok(p.historyAvailable(55477));
});

test('page history: a 404 or an unknown schema is "no history", kept, and hides the glance link (S8)', async () => {
  for (const a of [{ status: 404 }, { status: 200, body: { schema: 2, teamID: 55477, squads: [] } }, { status: 200, body: { ...DOC, teamID: 1 } }]) {
    const p = page(() => a);
    assert.equal(await p.getTeamHistory(55477), null);
    assert.equal(await p.getTeamHistory(55477), null);
    assert.equal(p.apiCalls().length, 1, JSON.stringify(a));
    assert.equal(p.historyAvailable(55477), false);
    assert.equal(p.historyAvailable(54493), true);
  }
});

test('page history: a refusal rejects with "try again", is remembered for a minute, never a fallback', async () => {
  for (const status of [429, 400, 403]) {
    const p = page(() => ({ status }));
    const e = await p.getTeamHistory(55477).then(() => null, err => err);
    assert.equal(e.status, status);
    assert.ok(p.isRefusal(e));
    for (let i = 0; i < 10; i++) await assert.rejects(p.getTeamHistory(55477));
    assert.equal(p.apiCalls().length, 1, `${status}: one request for a minute`);
    assert.ok(p.historyAvailable(55477), 'a refusal never hides the link');
    p.clock.t += 60000;
    await assert.rejects(p.getTeamHistory(55477));
    assert.equal(p.apiCalls().length, 2);
    assert.ok(p.apiCalls().every(c => c === 'GET /api/v1/teams/55477/history'), 'nothing else is asked');
  }
  const p = page(() => ({ status: 429 }));
  assert.equal(p.retryText(await p.getTeamHistory(55477).catch(e => e)), 'Too many requests. Try again in a minute.');
});

test('page history: a 503, a network error or bad JSON rejects and is asked again next time', async () => {
  for (const a of [{ status: 503 }, new TypeError('network'), { status: 200, raw: '{not json' }]) {
    const p = page(() => a);
    await assert.rejects(p.getTeamHistory(55477));
    await assert.rejects(p.getTeamHistory(55477));
    assert.equal(p.apiCalls().length, 2, String(a.status || a.message || 'bad json'));
    assert.ok(p.historyAvailable(55477));
  }
});

// ---- the words: M4, S2 ----
const words = new Function(block('    function historyYears(', 'function historyOutcome(') + '\nreturn { historyYears, historyOutcome, historyStamp };')();

// The "One TGS id, N squads" note (#107 re-check): a carry only when the same id is in the same
// age group a season later at the 2026-27 regroup; otherwise the age groups say what happened.
test('page history: the "One TGS id" note follows the age groups', { skip: !hasHistory && 'no team-history data in this checkout' }, async () => {
  const splitNotes = new Function('seasonLabel', block('    function historySplitNotes(') + '\nreturn historySplitNotes;')(s => s.replace('-', '–'));
  const age = r => `U${r.u}`;
  const notes = async id => splitNotes((await json(`archive/history/${id}.json`)).squads, id, age);
  const carry = /kept it in the same age group/;
  // Not carries: a different age group across the regroup, or no 2025-26 row at all.
  assert.deepEqual(await notes(34961), ['In 2026–27 TGS reused it for another age group (U18 in 2025–26, U13 in 2026–27).']);
  assert.deepEqual(await notes(82349), ['In 2026–27 TGS reused it for another age group (U14 in 2025–26, U13 in 2026–27).']);
  assert.deepEqual(await notes(46765), ['In 2026–27 TGS reused it for another age group (U17 in 2024–25, U18 in 2026–27).']);
  // The earlier reuses: two age groups up, and a gap of two seasons.
  assert.deepEqual(await notes(19409), ['In 2021–22 TGS reused it for another age group (U16 in 2020–21, U18 in 2021–22).']);
  assert.deepEqual(await notes(46961), ['In 2022–23 TGS reused it for another age group (U13 in 2021–22, U15 in 2022–23).']);
  assert.deepEqual(await notes(12596), ['In 2025–26 TGS reused it for another age group (U18 in 2022–23, U13 in 2025–26).']);
  // Carries (controls): the same age group a season later, across the regroup.
  assert.match((await notes(94620))[0], carry);
  assert.deepEqual((await notes(46817)).map(n => carry.test(n) ? 'carry' : n),
    ['In 2021–22 TGS kept it for its age slot (U13) rather than for one group of players.', 'carry']);
  for (const id of [34961, 82349, 46765, 19409, 46961, 12596]) assert.ok(!(await notes(id)).some(n => carry.test(n) || /did not move up/.test(n)), id);
});

test('page history: "History as of" gives the date and the UTC time', () => {
  assert.equal(words.historyStamp('2026-09-30T19:55:34Z'), 'Sep 30, 2026, 7:55 PM UTC');
  assert.equal(words.historyStamp(null), '');
});

test('page history: a post-season entry says only what the bracket decided (M4)', () => {
  const o = e => words.historyOutcome({ tier: 'Champions League', ...e }).text;
  assert.equal(o({ champion: true, reached: 'Final' }), '🏆 Champion');
  assert.equal(o({ reached: 'Final', final: 'lost' }), 'Runner-up');
  assert.equal(o({ reached: 'Final', final: 'undecided' }), 'Reached the Final (no result published)');
  assert.equal(o({ reached: 'Final', final: 'undecided', inProgress: true }), 'Reached the Final (to play)');
  assert.equal(o({ reached: 'Final' }), 'Reached the Final');
  assert.equal(o({ reached: 'Round of 16', group: { name: 'Group B', pos: 1, of: 4 } }), '1st of 4 in Group B, then the Round of 16');
  assert.equal(o({ reached: 'First round' }), 'Reached the first round');
  assert.equal(o({ group: { name: 'Group G', pos: 4, of: 4 } }), 'Group stage · 4th of 4 in Group G');
  assert.equal(o({ tier: 'Showcase Games', group: { name: '', pos: 15, of: 18 } }), 'No title at stake');
  assert.equal(words.historyOutcome({ reached: 'Final', final: 'undecided' }).short, 'Final');
  assert.equal(words.historyYears([2011]), '2011');
  assert.equal(words.historyYears([2010, 2011]), '2010/11');
});
